services:
  - type: web
    name: https://github.com/Mike352-design/X-BOT-MD
    env: docker
    region: Frankfurt
    plan: free
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUDO
        sync: false
